SELECT ?hypothesis ?graph ?s1 ?s2 ?s ?p ?o
WHERE {
    GRAPH ?h {
        ?s1 <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?r1 .
        ?r1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Restriction> ;
            <http://www.w3.org/2002/07/owl#onProperty> <http://purl.obolibrary.org/obo/apo.owl#implies> ;
            <http://www.w3.org/2002/07/owl#someValuesFrom> ?s2 .
    
        
    }
    BIND(IRI(REPLACE(STR(?h),
        "http://hypo.project-genesis.io/",
        "http://hypo.project-genesis.io/hypothesis-metadata/"
    )) AS ?hypothesis)

    GRAPH ?graph {
        ?s ?p ?o .
    }
}'